Field.create(name: 'Sent Church', location: '3701 W Spring Creek Pkwy Plano, TX 75023')
Field.create(name: 'Bakersfield #5', location: '1201 Duncan Lane, Flower Mound, TX 75028')
Field.create(name: 'Frisco 1A', location: '7255 Meadow Hill Frisco, TX 75034')
Field.create(name: 'Frisco 1C', location: '7255 Meadow Hill Frisco, TX 75034')
Field.create(name: 'Frisco #2', location: '7255 Meadow Hill Frisco, TX 75034')
Field.create(name: 'Frisco #3', location: '7255 Meadow Hill Frisco, TX 75034')
Field.create(name: 'Frisco #4', location: '7255 Meadow Hill Frisco, TX 75034')
Field.create(name: 'PIT Plano #1', location:  '4401 14th St Plano, TX 75074')
Field.create(name: 'PIT Plano #10', location: '4401 14th St Plano, TX 75074')
Field.create(name: 'PIT Plano #11', location: '4401 14th St Plano, TX 75074')
Field.create(name: 'PIT Plano #12', location: '4401 14th St Plano, TX 75074')
Field.create(name: 'PIT Plano #13', location: '4401 14th St Plano, TX 75074')
Field.create(name: 'PIT Plano #14', location: '4401 14th St Plano, TX 75074')
Field.create(name: 'PIT Plano #16', location: '4401 14th St Plano, TX 75074')
Field.create(name: 'PIT Plano #2', location: '4401 14th St Plano, TX 75074')
Field.create(name: 'PIT Plano #3', location: '4401 14th St Plano, TX 75074')
Field.create(name: 'PIT Plano #4', location: '4401 14th St Plano, TX 75074')
Field.create(name: 'PIT Plano #7', location: '4401 14th St Plano, TX 75074')
Field.create(name: 'PIT Plano #8', location: '4401 14th St Plano, TX 75074')
Field.create(name: 'PIT Plano #9', location: '4401 14th St Plano, TX 75074')
Field.create(name: 'Railroad Park 1a', location: '1301 S Railroad Street Lewisville, TX 75067')
Field.create(name: 'Railroad Park 2a', location: '1301 S Railroad Street Lewisville, TX 75067')
Field.create(name: 'Railroad Park 2b', location: '1301 S Railroad Street Lewisville, TX 75067')
Field.create(name: 'Railroad Park 3a', location: '1301 S Railroad Street Lewisville, TX 75067')
Field.create(name: 'Railroad Park 3b', location: '1301 S Railroad Street Lewisville, TX 75067')
Field.create(name: 'Railroad Park 4a', location: '1301 S Railroad Street Lewisville, TX 75067')
Field.create(name: 'Carpenter A', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter B', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter B1', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter C', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter D', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter E', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter F', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter G', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter H', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter I', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter J', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter J2', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter K', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter L', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Carpenter M', location: '6701 Coit Road Plano, TX 75023')
Field.create(name: 'Cheyenne B', location: '2501 Mission Ridge Rd, Plano, TX 75075')
Field.create(name: 'Cheyenne C', location: '2501 Mission Ridge Rd, Plano, TX 75075')
Field.create(name: 'Cheyenne F', location: '2501 Mission Ridge Rd, Plano, TX 75075')
Field.create(name: 'Russell Creek A', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek B', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek C', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek D', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek E', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek F', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek G', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek H', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek I', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek J', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek K', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek L', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek M', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek N', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek O', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek P', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek R', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek U', location: '3500 McDermott Road Plano, TX 75025')
Field.create(name: 'Russell Creek V', location: '3500 McDermott Road Plano, TX 75025')

Club.create(name: 'Tornados FC')
Club.create(name: 'Solar')
Club.create(name: 'FC Dallas')
Club.create(name: 'PAYD')
Club.create(name: 'Alphaforms')
Club.create(name: 'HPSA Scots')
Club.create(name: 'FC Fast')
Club.create(name: 'Dallas Tigres Academy')
Club.create(name: 'Texas United')
Club.create(name: 'NTX Warriors') 
Club.create(name: 'Sporting United SC')
Club.create(name: 'McKinney Soccer MSC')
Club.create(name: 'FC Premier')
Club.create(name: 'City FC')
Club.create(name: 'NTX Celtic FC') 
Club.create(name: 'Dutch Lions FC')
Club.create(name: 'Forney SA Forney Elite FC')
Club.create(name: 'Dallas Roma FC')
Club.create(name: 'Dallas Rush')
Club.create(name: 'Club America') 
Club.create(name: 'Coppell FC')
Club.create(name: 'Fever United')
Club.create(name: 'Dallas Kicks')
Club.create(name: 'Liverpool FC')
Club.create(name: 'Garland Tigres Academy') 
Club.create(name: 'Frisco Fusion')
Team.create(name: 'Tornados FC 08 Boys', club_id: 1)
Team.create(name: 'Tornados FC 05 Boys', club_id: 1)
Team.create(name: 'Tornados FC 12 Boys', club_id: 1)
Team.create(name: 'Tornados FC 11 Boys', club_id: 1)
Team.create(name: 'Solar 12B Perry Black', club_id: 2)
Team.create(name: 'PAYD 12 Boys', club_id: 4)
Team.create(name: 'FC Dallas 12B Wright', club_id: 3)
Team.create(name: 'FC Dallas Red - Fernandez 12B', club_id: 3)
Team.create(name: 'Forms Academy Alphaforms 12', club_id: 5)
Team.create(name: 'FC Dallas 12B Ramirez', club_id: 3)
Team.create(name: 'Solar East 12B Jordan', club_id: 2)
Team.create(name: 'Solar 12B Perry Grey', club_id: 2)
Team.create(name: 'HPSA Scots 11B', club_id: 6)
Team.create(name: 'FC Dallas 11B Griffin', club_id: 3)
Team.create(name: 'FC Dallas 11B Perez', club_id: 3)
Team.create(name: 'FC Fast 11', club_id: 7)
Team.create(name: 'Dallas Tigres Academy Mesquite 11B Gold', club_id: 8)
Team.create(name: 'FC Dallas 11B Ramirez', club_id: 3)
Team.create(name: 'Texas United 11B', club_id: 9)
Team.create(name: 'NTX Warriors 08B', club_id: 10)
Team.create(name: 'Sporting United 08 Hale', club_id: 11)
Team.create(name: 'FC Dallas Youth 08B Central Blue', club_id: 3)
Team.create(name: 'McKinney Soccer MSC 08B', club_id: 12)
Team.create(name: 'FC Premier 08B', club_id: 13)
Team.create(name: 'City FC 08B (Guarda)', club_id: 14)
Team.create(name: 'FC Dallas Youth 08B North White', club_id: 3)
Team.create(name: 'NTX Celtic FC 08 High', club_id: 15)
Team.create(name: 'FC Dallas Youth 08B North Red', club_id: 3)
Team.create(name: 'Dutch Lions FC 08B', club_id: 16)
Team.create(name: 'Forney SA Forney Elite FC 08B', club_id: 17)
Team.create(name: 'Dallas Tigres Academy 08 Gold (Guerrero)', club_id: 8)
Team.create(name: 'Dallas Roma FC 08B Beta', club_id: 18)
Team.create(name: 'Dallas Rush 08 Rangira', club_id: 19)
Team.create(name: 'Club America Premier 08B', club_id: 20)
Team.create(name: 'FC Dallas Youth 08B Central', club_id: 3)
Team.create(name: 'Coppell FC 08B Red', club_id: 21)
Team.create(name: 'FC Dallas Youth 08B Central Red', club_id: 3)
Team.create(name: 'Fever United 05B T Smith', club_id: 22)
Team.create(name: 'Dallas Kicks 05B Desafio', club_id: 23)
Team.create(name: 'Liverpool 05 Boys Melia', club_id: 24)
Team.create(name: 'Garland Tigres Academy GTA 05B White', club_id: 25)
Team.create(name: 'Frisco Fusion 05B', club_id: 26)
Team.create(name: 'FC Dallas Youth 05B White', club_id: 3)
Team.create(name: 'FC Dallas Youth 05B North White', club_id: 3)
Team.create(name: 'FC Dallas Youth 05 Black', club_id: 3)
Team.create(name: 'NTX Celtic FC 05B Duke', club_id: 15)


Player.create(name: 'Myles Balch', number: 19, team_id: 1)
Player.create(name: 'Caden Boyd', number: 21, team_id: 1)
Player.create(name: 'Rehan Buvvaji', number: 10, team_id: 1)
Player.create(name: 'Ayan Gautam', number: 2, team_id: 1)
Player.create(name: 'Nash Hornberger', number: 6, team_id: 1)
Player.create(name: 'Arbes Kambo', number: 7, team_id: 1)
Player.create(name: 'Canon Leverett', number: 15, team_id: 1)
Player.create(name: 'Alex Osborn', number: 3, team_id: 1)
Player.create(name: 'Jeremiah Princewill', number: 23, team_id: 1)
Player.create(name: 'Spencer Ruml', number: 14, team_id: 1)
Player.create(name: 'Sam Schewee', number: 13, team_id: 1)
Player.create(name: 'Blayse Smith', number: 18, team_id: 1)
Player.create(name: 'Colin Sun', number: 4, team_id: 1)
Player.create(name: 'Patton Ma-Hain', number: 9, team_id: 1)

Player.create(name: 'Jai Ahuja', number: 18, team_id: 2)
Player.create(name: 'Enzo Alvarez', number: 10, team_id: 2)
Player.create(name: 'Luke Armstrong', number: 7, team_id: 2)
Player.create(name: 'Jacob Carlson', number: 8, team_id: 2)
Player.create(name: 'Jeffrey Collins', number: 12, team_id: 2)
Player.create(name: 'Nicholas Echaniz', number: 9, team_id: 2)
Player.create(name: 'Logan Fabrega', number: 16, team_id: 2)
Player.create(name: 'Quinton Hammonds', number: 14, team_id: 2)
Player.create(name: 'Anthony Kenneth', number: 23, team_id: 2)
Player.create(name: 'Adam Khan', number: 25, team_id: 2)
Player.create(name: 'James Manchee', number: 15, team_id: 2)
Player.create(name: 'Patrick McGuigan', number: 21, team_id: 2)
Player.create(name: 'Thomas Melvin', number: 13, team_id: 2)
Player.create(name: 'Jeswant Ramesh', number: 19, team_id: 2)
Player.create(name: 'Jewlyen Thomas-Roberts', number: 6, team_id: 2)
Player.create(name: 'Walker Williams', number: 11, team_id: 2)
Player.create(name: 'Trevor Jobe', number: 5, team_id: 2)

Player.create(name: 'Jax Adams', number: 7, team_id: 3)
Player.create(name: 'Callen Files', number: 8, team_id: 3)
Player.create(name: 'Duncan Ma-Hain', number: 9, team_id: 3)
Player.create(name: 'Leo Lopez', number: 10, team_id: 3)
Player.create(name: 'Tristan Amend', number: 21, team_id: 3)
Player.create(name: 'Luke Hingson', number: 25, team_id: 3)

Player.create(name: 'Daniel Monastrirsky', number: 2, team_id: 4)
Player.create(name: 'Tristan Beck', number: 3, team_id: 4)
Player.create(name: 'Evan Tran', number: 5, team_id: 4)
Player.create(name: 'Brayden Emmons', number: 7, team_id: 4)
Player.create(name: 'Oscar Berbarie', number: 8, team_id: 4)
Player.create(name: 'Wyatt York', number: 9, team_id: 4)
Player.create(name: 'Shlok Dharmadhikari', number: 10, team_id: 4)
Player.create(name: 'Landon Cacioppo', number: 13, team_id: 4)
Player.create(name: 'Rylan Boy', number: 21, team_id: 4)


Practice.create(team_id: 1, field_id: 1, date: 'Tuesday and Thursday', time: '7-8:15')
Practice.create(team_id: 2, field_id: 1, date: 'Monday and Wednesday', time: '7-8:15')
Practice.create(team_id: 3, field_id: 1, date: 'Tuesday and Thursday', time: '6-7')
Practice.create(team_id: 4, field_id: 1, date: 'Monday and Wednedsday', time: '6-7')

Game.create(home_id: 5, away_id: 3, field_id: 2, date: '2/16/2019', time: '4:00pm')
Game.create(home_id: 3, away_id: 6, field_id: 7, date: '2/23/2019', time: '12:00pm')
Game.create(home_id: 3, away_id: 7, field_id: 17, date: '3/2/2019', time: '8:00am')
Game.create(home_id: 8, away_id: 3, field_id: 7, date: '3/23/2019', time: '5:00pm')
Game.create(home_id: 3, away_id: 9, field_id: 7, date: '3/30/2019', time: '3:00pm')
Game.create(home_id: 10, away_id: 3, field_id: 16, date: '4/6/2019', time: '6:00pm')
Game.create(home_id: 3, away_id: 11, field_id: 17, date: '4/13/2019', time: '3:00pm')
Game.create(home_id: 12, away_id: 3, field_id: 16, date: '4/27/2019', time: '1:00pmß')

Game.create(home_id: 4, away_id: 13, field_id: 11)
# Game.create(home_id: 5, away_id: 1, field_id: 2)
# Game.create(home_id: 5, away_id: 1, field_id: 2)
# Game.create(home_id: 5, away_id: 1, field_id: 2)
# Game.create(home_id: 5, away_id: 1, field_id: 2)
# Game.create(home_id: 5, away_id: 1, field_id: 2)
# Game.create(home_id: 5, away_id: 1, field_id: 2)
# Game.create(home_id: 5, away_id: 1, field_id: 2)
# Game.create(home_id: 5, away_id: 1, field_id: 2)
